services:
  nginx:
    image: nginx:1.28.0
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - php
    ports:
      - ${APP_PORT:-8080}:80
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        - APP_ENV=${APP_ENV:-prod}
      target: ${APP_ENV:-prod}
    volumes:
      - ./:/var/www/html
    environment:
       APP_ENV: ${APP_ENV:-prod}
    networks:
      - default

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
