services:
  nginx:
    container_name: glpi-nginx
    image: nginx:1.28.0
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - glpi-app-net

  php:
    container_name: glpi-php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - glpi-app-net

  db:
    container_name: glpi-db
    image: "mariadb:11.4"
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
      # - ".docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOB_PASSWORD:-glpi}
      MARIADB_DATABASE: ${DB_NAME:-glpi}
      MARIADB_USER: ${DB_USER:-glpi}
      MARIADB_PASSWORD: ${DB_PASSWORD:-glpi}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      - glpi-app-net

volumes:
  db:

networks:
  glpi-app-net:
    name: glpi-app-net
